language: php

php:

  - 5.5

before_install:

  - openssl aes-256-cbc -k "${KEY_PASSWORD}" -d -a -in ./ci/new-key.enc -out new-key
  - echo -e "Host github.com\n  IdentityFile ${TRAVIS_BUILD_DIR}/ci/new-key" > ~/.ssh/config
  - cat ~/.ssh/config
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - sudo apt-get update > /dev/null

script:

  - make lint

notifications:

  slack: a8c:rdeQR68xgiffkssb1ZNw5P1c

KEY_PASSWORD=ef12a5e132f14d2aab2e0719f99f724a4d9d0f8fb39c0fcdb63b50463ab800ed:
  secure: nQnswFRMSK+cbbMNUmqR8Kegfq+rE16lcgK3iTdsMof1zz6O/yreQRKt0DFaX+3UoTKh+4GPj+BlVtuEhhUwUfa9BtWdlQy91v8XOVgMHN4YnCZWiJlEYcBbNMS4lxCmxH5ez3lkdUWxjVx2oN8kNKKei7FfMIZeK+89BS430mE=
