language: php

git:
  submodules: false

php:
  - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update > /dev/null
  - ./ci/prepare.sh

script:
- make lint

  # PHPUnit
  - make phpunit

notifications:
#  slack: a8c:rdeQR68xgiffkssb1ZNw5P1c

