language: php

git:
  submodules: false

php:
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_install:
  - mkdir -p ~/.ssh
  - mkdir -p ~/.ssh-archive
  - mv -v ~/.ssh/id_rsa ~/.ssh-archive/id_rsa*
  - ssh-add -D
  - echo -e "Host github.com\n  User wpcomvip-deploy\n  IdentityFile ${TRAVIS_BUILD_DIR}/ci/ssh/insecure-key\n" > ~/.ssh/config
  - chmod 600 ${TRAVIS_BUILD_DIR}/ci/ssh/*
  - cat ~/.ssh/config
  - cp ${TRAVIS_BUILD_DIR}/ci/ssh/known_hosts ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - ls -alh ~/.ssh
  - ssh -v -T git@github.com
  - whoami
  - git clone git@github.com:Automattic/vip-dashboard.git
  - git clone git@github.com:Automattic/vipv2-support.git
  - git clone git@github.com:Automattic/vipv2-jetpack.git
#  - git submodule update --init --recursive
  - sudo apt-get update > /dev/null
  - ./ci/prepare.sh

script:

  - make test

  # PHPUnit
  - make phpunit

# notifications:
#
#  slack: a8c:rdeQR68xgiffkssb1ZNw5P1c

