language: php
sudo: false # Use modern Travis builds – http://docs.travis-ci.com/user/migrating-from-legacy/

git:
  submodules: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0 DEPLOY_BRANCH=master

before_install:
  - ./ci/prepare.sh
  - git submodule update --init --recursive

script:
  # Linting and unit tests
  - make test

notifications:

  slack: a8c:Hhd7rqdnXOFQgEU4HNZvkGs7
