language: php
env:
  global:
      secure: "mkLA/hO4+ETG2TXuVUsck1qAYXo+vEihK+XlKbFrxwmmiXaF5k6ooRRjTkkMBGQYckqE8JsY9E4VXUOk+NnhEXP6iMrXRB0CD8/l9iICFkKpRfgNc2eZHHSz/mDsVFdDLQEbv30Lxcfsuf5mv2ppYyotILNh8xhj+R/V/jm00k8="

git:
  submodules: false

php:
  - 5.5

before_install:
  - echo $KEY_PASSWORD
  - cat "${TRAVIS_BUILD_DIR}/ci/new-key.enc"
  - openssl aes-256-cbc -k "${KEY_PASSWORD}" -d -a -in "${TRAVIS_BUILD_DIR}/ci/new-key.enc" -out ${TRAVIS_BUILD_DIR}/ci/new-key
  - echo -e "Host github.com\n  IdentityFile ${TRAVIS_BUILD_DIR}/ci/new-key" > ~/.ssh/config
  - cat ~/.ssh/config
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts
  - cat ~/.ssh/known_hosts
  - git submodule update --init --recursive
  - sudo apt-get update > /dev/null

script:
- make lint

notifications:
  slack: a8c:rdeQR68xgiffkssb1ZNw5P1c

